### ISSUE TITLE
Error when right clicking in the store menu.

### ISSUE THREAD

**Issue by enels0n** [pablo67340/GUIShop#129]
https://pastebin.com/z2np72he

Latest version of the plugin.

It also displays a warning when closing any menu.
https://pastebin.com/hP1BA9LP

Type /shop Heads -> https://pastebin.com/dasQJSDL

The existing NBT does not work in 1.21.1, but issuing the same item using a command does work.
```
        '19': # ✔
          type: SHOP
          id: CHEST
          buy-price: 25000
          shop-name: "&6Golden Apple &rPre-Filled Chest"
          commands:
            - 'minecraft:give %player_name% chest[container=[{slot:0,item:{id:"golden_apple",count:64}}]] 1'
        '20': # ❌
          type: SHOP
          id: CHEST
          buy-price: 10000
          shop-name: "&fDirt &rPre-Filled Chest"
          custom-nbt: '{BlockEntityTag:{Items:[{Slot:0,id:"dirt",Count:64}]}}'
```
