### ISSUE TITLE
Shop purchased items don't stack with non-purchased items

### ISSUE THREAD

**Issue by Parsonswy** [pablo67340/GUIShop#39]
We just updated to GUIShop 7.3.5 and items purchased in `/buy` won't stack with normal game items. IE, break a block of dirt off the ground, then buy a block of dirt from the shop. The items will not stack in the player's inventory.

The same is true for different quantities of the same item that are purchased. IE; buy 1 block of dirt, then buy 2 blocks of dirt. The one block of dirt will not go into the stack with two blocks of dirt.

If the items are placed and then broken they can be combined again. All of the items in our shop behave like this. Below is a sample of our shop.yml configuration. 

```YAML
Blocks:
  0:
    id: GRASS_BLOCK
    slot: 0
    buy-price: 0.25
    sell-price: 0.25
    type: SHOP
  1:
    id: DIRT
    slot: 1
    buy-price: 0.25
    sell-price: 0.25
    type: SHOP
```
