### ISSUE TITLE
Items Do Not Load If Too Many: ArrayIndexOutOfBounds

### ISSUE THREAD

**Issue by A248** [pablo67340/GUIShop#53]
**This is an issue posted by another user in the GUIShop discord, I'm adding it here so that it can be more easily managed – A248**

------------------------------

no matter what the 89th entry is (i've tried perfectly valid ones that I know work from earlier in the config), it doesn't load in any items past the 70th if I have an 89th entry at all and throws:

yaml validators are fine, i'm certain the 89th entry isn't invalid or anything.

section of config in question (88):
```yaml
  '87':
    type: SHOP
    id: QUARTZ_SLAB
    buy-price: 2.0
    sell-price: 1.0
  '88':
    type: SHOP
    id: QUARTZ_SLAB
    buy-price: 2.0
    sell-price: 1.0
```

Stacktrace: https://pastebin.com/9QUqnrFL
Config: https://pastebin.com/HQTv5j21

Paper 151 - 1.15.2
GUIShop 7.3.8
